### ISSUE TITLE
Error: Cannot find module './lib/google.js

### ISSUE THREAD

**Issue by aboobakkar** [BlueRival/node-google-url#4]
Error: Cannot find module './lib/google.js'
W20170411-15:28:54.187(5.5)? (STDERR)     at require (packages/modules-runtime.js:123:19)
W20170411-15:28:54.188(5.5)? (STDERR)     at meteorInstall.node_modules.google-url.index.js (packages/modules.js:525:18)
W20170411-15:28:54.189(5.5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170411-15:28:54.190(5.5)? (STDERR)     at require (packages/modules-runtime.js:120:16)
W20170411-15:28:54.191(5.5)? (STDERR)     at meteorInstall.imports.api.Userdata.js (imports/api/Userdata.js:4:17)
W20170411-15:28:54.191(5.5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170411-15:28:54.192(5.5)? (STDERR)     at Module.require (packages/modules-runtime.js:120:16)
W20170411-15:28:54.194(5.5)? (STDERR)     at Module.Mp.import (/home/aboo/.meteor/packages/modules/.0.7.9.1gwdgyf++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:75:16)
W20170411-15:28:54.195(5.5)? (STDERR)     at meteorInstall.server.main.js (server/main.js:1:1)
W20170411-15:28:54.195(5.5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.

**Comment by hildoer** [comment]
We are no longer performing active development on this library. If you have a fix you can create a pull request and we will publish it. Make sure to update and/or add tests to cover your changes.
