### ISSUE TITLE
Minor: typo in usage example (GoogleUrl and GoogleURL)

### ISSUE THREAD

**Issue by ellenaua** [BlueRival/node-google-url#5]
There's a typo and code does not work

var GoogleUrl = require( 'google-url' );
googleUrl = new GoogleURL();

**Comment by MaxySpark** [comment]
did u fix this?
I'm getting `GoogleURL is not defined`

**Comment by AlexeyKorkoza** [comment]
I found resolving the problem.
You must write the next way:

```
var GoogleUrl = require('google-url'); 
var googleUrl = new GoogleUrl();

```

Good Luck
