### ISSUE TITLE
Is this project is still actual?

### ISSUE THREAD

**Issue by yourmummy** [BlueRival/node-google-url#7]
I'm not quite sure, but it seems that is not working right now.
I've just copypaste example, add my google token

```javascript
...

const GoogleUrl = require('google-url');
const googleUrl = new GoogleUrl( { key: config.get('token') });

googleUrl.shorten( 'http://bluerival.com/', (err, shortUrl) => {
    console.log(err, shortUrl)
});
```
And this return "Forbidden, undefined".
It seems google change something in api. Do you plan to update your project?

**Comment by sabado** [comment]
I also have the same return Forbidden, undefined

-------------------------------------------------------------
founded this article from developers google blog. 

**Transitioning Google URL Shortener to Firebase Dynamic Links.** 
https://developers.googleblog.com/2018/03/transitioning-google-url-shortener.html

**Comment by hildoer** [comment]
We are no longer performing active development on this library. If you have a fix you can create a pull request and we will publish it. Make sure to update and/or add tests to cover your changes.
